using SentinelKey.Contracts.Enrollment;

namespace SentinelKey.Application.Enrollment.CreateEnrollmentSession;

public sealed record CreateEnrollmentSessionResult(EnrollmentSessionResponse EnrollmentSession);
